feat: Adds `Button` docs
vtex-sites/gatsby.store pull request #52
Opened 2022-05-19 18:14 UTC by lucasfp13

## What's the purpose of this pull request?

<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>

## How does it work?

<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?

<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>

## References

<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

## Checklist

<em>You may erase this after checking them all ;)</em>

- [ ] Added an entry in the `CHANGELOG.md` at the beginning of its due section. [The latest version should comes first](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first.).
- [ ] Added the PR number with the PR link at the entry in the `CHANGELOG.md`. E.g., *New items in the `pull_request_template.md` ([#12](https://github.com/vtex-sites/gatsby.store/pull/12))* 

- PR description
- [ ] Updated the Storybook - *if applicable*.
- [ ] Added a label according to the PR goal - `Breaking change`, `Enhancement`, `Bug` or `Chore`.
- [ ] Added the component, hook, or pathname in-between backticks (``) *- If applicable*. E.g., *`ComponentName` component*.
- [ ] Identified the function or parameter in the PR *- If applicable*. E.g., *`useWindowDimensions` hook*.
- [ ] For documentation changes, ping @carolinamenezes or @Mariana-Caetano to review and update the changes.

2022-05-30 18:25 UTC, ArthurTriis1 approved these changes

2022-05-31 00:36 UTC, hellofanny commented on src/components/ui/Button/Button.stories.mdx
> +A element that allows users to take actions, make choices or trigger an event with a single tap.
```suggestion
This component allows users to take actions, make choices, or trigger an event with a single tap.
```

2022-05-31 00:37 UTC, hellofanny commented on src/components/ui/Button/Button.stories.mdx
> +| <code>--fs-button-text-weight</code>         | <code>bold</code>                                                                                 |
```suggestion
| <code>--fs-button-text-weight</code>         | <code>var(--fs-text-weight-bold)</code>                                                                                 |
```

2022-05-31 00:39 UTC, hellofanny commented on src/components/ui/Button/Button.stories.mdx
> +| <code>--fs-button-text-weight</code>         | <code>bold</code>                                                                                 |
Can you also update here pls? Thanks.


https://github.com/vtex-sites/gatsby.store/blob/d2eab5cf901a9969332c97565b091774ae2d1912/src/components/ui/Button/button.scss#L21

2022-05-31 00:44 UTC, hellofanny commented on src/components/ui/Button/Button.stories.mdx
> +| <code>--fs-button-border-radius</code>       | <code>var(--fs-border-radius-default)</code>                                                      |
```suggestion
| <code>--fs-button-border-radius</code>       | <code>var(--fs-border-radius)</code>                                                      |
```

2022-05-31 00:54 UTC, hellofanny requested changes
Niceee! I've left a few suggestions, can you please take a look?

Shouldn't we also list `disabled` as a variation?

![image](https://user-images.githubusercontent.com/3356699/171072402-15fcf112-3fb6-43d5-bd2c-80e8117fb70c.png)

2022-05-31 21:34 UTC, renatamottam approved these changes
Amazing work! Just left a fix to follow our pattern 🙃

2022-05-31 21:34 UTC, renatamottam commented on src/components/ui/Button/button.module.scss
> +.fs-button[data-fs-button] {
No need for the `data-attribute` here! See `product-card.module.scss` as reference.
```suggestion
.fs-button {
```

2022-06-01 00:17 UTC, eduardoformiga commented on src/components/ui/Button/Button.stories.mdx
> +- [Related Components](#related-components)
Nice! 

@renatamottam should we add this section from now on?

2022-06-01 00:19 UTC, eduardoformiga approved these changes
Great Job! 👏 

LGTM after applying @renatamottam  suggestions.

2022-06-01 19:02 UTC, hellofanny commented on src/components/ui/Button/Button.tsx
> +   * For accessibility purposes, defines an ARIA label to the element when no label is provided
```suggestion
   * For accessibility purposes, defines an ARIA label to the button when no label is provided
```

2022-06-01 19:07 UTC, hellofanny approved these changes
Well done @lucasfp13 !!! 🚀🚀🚀 
I liked the `Related Components` section idea :) 

What do you think of adding a sample of usage of Button only with an icon (without label)? We could add an example with an aria-label for this case.

![image](https://user-images.githubusercontent.com/3356699/171482591-c5846381-e88d-416b-b616-c8a82d136e47.png)

2022-06-03 12:58 UTC, merged