chore: Single UI Provider
vtex-sites/gatsby.store pull request #93
Opened 2022-06-06 20:07 UTC by tlgimenes

## What's the purpose of this pull request?

<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>

## How does it work?

<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?

<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>

## References

<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

## Checklist

<em>You may erase this after checking them all ;)</em>

- [ ] Added an entry in the `CHANGELOG.md` at the beginning of its due section. [The latest version should comes first](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first.).
- [ ] Added the PR number with the PR link at the entry in the `CHANGELOG.md`. E.g., *New items in the `pull_request_template.md` ([#12](https://github.com/vtex-sites/gatsby.store/pull/12))* 

- PR description
- [ ] Updated the Storybook - *if applicable*.
- [ ] Added a label according to the PR goal - `Breaking change`, `Enhancement`, `Bug` or `Chore`.
- [ ] Added the component, hook, or pathname in-between backticks (``) *- If applicable*. E.g., *`ComponentName` component*.
- [ ] Identified the function or parameter in the PR *- If applicable*. E.g., *`useWindowDimensions` hook*.
- [ ] For documentation changes, ping @ carolinamenezes, @ PedroAntunesCosta or @ Mariana-Caetano to review and update the changes.

2022-06-07 16:50 UTC, danzanzini requested changes
Requesting changes due to the scroll problem at the PDP. I've left one comment regarding this on code.

2022-06-07 18:30 UTC, tlgimenes commented on src/sdk/ui/modal/Provider.tsx
> -      layout.current?.classList.remove('no-scroll')
nice catch! I'll take a look why

2022-06-08 15:57 UTC, tlgimenes commented
Oh @danzanzini , I think it's working now :)

2022-06-08 18:05 UTC, danzanzini approved these changes
🚀

2022-06-08 18:42 UTC, merged